male(alan).
male(chris).
male(eoin).
male(fred).
male(isaac).
male(luke).
male(manik).
male(pete).

female(betty).
female(dina).
female(gemma).
female(hilda).
female(jenny).
female(katie).
female(nina).
female(olivia).

parent_of(isaac,manik).
parent_of(isaac,gemma).
parent_of(betty,manik).
parent_of(betty,gemma).
parent_of(fred,pete).
parent_of(fred,nina).
parent_of(jenny,pete).
parent_of(jenny,nina).
parent_of(eoin,betty).
parent_of(eoin,fred).
parent_of(olivia,betty).
parent_of(olivia,fred).
parent_of(chris,dina).
parent_of(chris,isaac).
parent_of(hilda,dina).
parent_of(hilda,isaac).
parent_of(luke,jenny).
parent_of(luke,alan).
parent_of(katie,jenny).
parent_of(katie,alan).