male(arnav).
male(chris).
male(edgar).
male(frank).
male(isaac).
male(luke).
male(mike).
male(peter).

female(beth).
female(donna).
female(gemma).
female(heather).
female(jenny).
female(katherine).
female(nancy).
female(olivia).

parent_of(isaac,mike).
parent_of(isaac,gemma).
parent_of(beth,mike).
parent_of(beth,gemma).
parent_of(frank,peter).
parent_of(frank,nancy).
parent_of(jenny,peter).
parent_of(jenny,nancy).
parent_of(edgar,beth).
parent_of(edgar,frank).
parent_of(olivia,beth).
parent_of(olivia,frank).
parent_of(chris,donna).
parent_of(chris,isaac).
parent_of(heather,donna).
parent_of(heather,isaac).
parent_of(luke,jenny).
parent_of(luke,arnav).
parent_of(katherine,jenny).
parent_of(katherine,arnav).